apiVersion: v1
kind: Service
metadata:
  name: multiplication-app-service
spec:
  selector:
    app: multiplication-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
