apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplication-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multiplication-app
  template:
    metadata:
      labels:
        app: multiplication-app
    spec:
      containers:
      - name: multiplication-app
        image: xkirk/multiplication-app:latest
        ports:
        - containerPort: 5000
